#!/bin/bash -e

# Settings
REPO_PATH=git@github.com:TUWien/ReadModules.git
GHPAGES_REPO_PATH=build/documentation
HTML_PATH=${GHPAGES_REPO_PATH}/html
COMMIT_USER="Documentation Builder"
COMMIT_EMAIL="travis@nomacs.org"
CHANGESET=$(git rev-parse --verify HEAD)

# Get a clean version of the HTML documentation repo.
rm -rf ${GHPAGES_REPO_PATH}
git clone -b gh-pages "${REPO_PATH}" --single-branch ${GHPAGES_REPO_PATH}
mkdir -p ${HTML_PATH}
# rm all the files through git to prevent stale files.
cd ${HTML_PATH}
git rm -rf .
cd -
# Generate the HTML documentation.
doxygen config/Doxyfile

# Create and commit the documentation repo.
cd ${GHPAGES_REPO_PATH}
git add .
git config user.name "${COMMIT_USER}"
git config user.email "${COMMIT_EMAIL}"
git commit -m "Automated documentation build for changeset ${CHANGESET}."
git push origin gh-pages
cd -
