var namespacerdm =
[
    [ "DkTestInfo", "classrdm_1_1_dk_test_info.html", "classrdm_1_1_dk_test_info" ],
    [ "BatchTest", "classrdm_1_1_batch_test.html", "classrdm_1_1_batch_test" ],
    [ "BinarizationPlugin", "classrdm_1_1_binarization_plugin.html", "classrdm_1_1_binarization_plugin" ],
    [ "FocusInfo", "classrdm_1_1_focus_info.html", "classrdm_1_1_focus_info" ],
    [ "FocusPlugin", "classrdm_1_1_focus_plugin.html", "classrdm_1_1_focus_plugin" ],
    [ "FormsInfo", "classrdm_1_1_forms_info.html", "classrdm_1_1_forms_info" ],
    [ "FormsAnalysis", "classrdm_1_1_forms_analysis.html", "classrdm_1_1_forms_analysis" ],
    [ "LayoutInfo", "classrdm_1_1_layout_info.html", "classrdm_1_1_layout_info" ],
    [ "LayoutPlugin", "classrdm_1_1_layout_plugin.html", "classrdm_1_1_layout_plugin" ],
    [ "PageData", "classrdm_1_1_page_data.html", "classrdm_1_1_page_data" ],
    [ "ColorButton", "classrdm_1_1_color_button.html", "classrdm_1_1_color_button" ],
    [ "ConfigWidget", "classrdm_1_1_config_widget.html", "classrdm_1_1_config_widget" ],
    [ "DirLabel", "classrdm_1_1_dir_label.html", "classrdm_1_1_dir_label" ],
    [ "XmlLabel", "classrdm_1_1_xml_label.html", "classrdm_1_1_xml_label" ],
    [ "PageProfileWidget", "classrdm_1_1_page_profile_widget.html", "classrdm_1_1_page_profile_widget" ],
    [ "TitledLabel", "classrdm_1_1_titled_label.html", "classrdm_1_1_titled_label" ],
    [ "PolygonWidget", "classrdm_1_1_polygon_widget.html", "classrdm_1_1_polygon_widget" ],
    [ "PolygonInfoWidget", "classrdm_1_1_polygon_info_widget.html", "classrdm_1_1_polygon_info_widget" ],
    [ "RegionWidget", "classrdm_1_1_region_widget.html", "classrdm_1_1_region_widget" ],
    [ "PageDock", "classrdm_1_1_page_dock.html", "classrdm_1_1_page_dock" ],
    [ "PageViewport", "classrdm_1_1_page_viewport.html", "classrdm_1_1_page_viewport" ],
    [ "PageVisPlugin", "classrdm_1_1_page_vis_plugin.html", "classrdm_1_1_page_vis_plugin" ],
    [ "SkewInfo", "classrdm_1_1_skew_info.html", "classrdm_1_1_skew_info" ],
    [ "SkewEstPlugin", "classrdm_1_1_skew_est_plugin.html", "classrdm_1_1_skew_est_plugin" ],
    [ "WIVocabulary", "classrdm_1_1_w_i_vocabulary.html", "classrdm_1_1_w_i_vocabulary" ],
    [ "WIDatabase", "classrdm_1_1_w_i_database.html", "classrdm_1_1_w_i_database" ],
    [ "WriterIdentification", "classrdm_1_1_writer_identification.html", "classrdm_1_1_writer_identification" ],
    [ "WIInfo", "classrdm_1_1_w_i_info.html", "classrdm_1_1_w_i_info" ],
    [ "WriterIdentificationPlugin", "classrdm_1_1_writer_identification_plugin.html", "classrdm_1_1_writer_identification_plugin" ]
];